DROP TABLE IF EXISTS isuumo.chairs_features;
DROP TABLE IF EXISTS isuumo.estates_features;
DROP TABLE IF EXISTS isuumo.chair_feature;
DROP TABLE IF EXISTS isuumo.estate_feature;

CREATE TABLE isuumo.chairs_features (chair_id INT NOT NULL, feature_id INT NOT NULL);
CREATE TABLE isuumo.estates_features (estate_id INT NOT NULL, feature_id INT NOT NULL);
-- CREATE TABLE isuumo.chair_feature (id INT NOT NULL AUTO_INCREMENT, feature VARCHAR(64) NOT NULL, PRIMARY KEY(id));
-- CREATE TABLE isuumo.estate_feature (id INT NOT NULL AUTO_INCREMENT, feature VARCHAR(64) NOT NULL, PRIMARY KEY(id));

-- INSERT INTO isuumo.chair_feature (feature) VALUES
--       ('ヘッドレスト付き'),
--       ('肘掛け付き'),
--       ('キャスター付き'),
--       ('アーム高さ調節可能'),
--       ('リクライニング可能'),
--       ('高さ調節可能'),
--       ('通気性抜群'),
--       ('メタルフレーム'),
--       ('低反発'),
--       ('木製'),
--       ('背もたれつき'),
--       ('回転可能'),
--       ('レザー製'),
--       ('昇降式'),
--       ('デザイナーズ'),
--       ('金属製'),
--       ('プラスチック製'),
--       ('法事用'),
--       ('和風'),
--       ('中華風'),
--       ('西洋風'),
--       ('イタリア製'),
--       ('国産'),
--       ('背もたれなし'),
--       ('ラテン風'),
--       ('布貼地'),
--       ('スチール製'),
--       ('メッシュ貼地'),
--       ('オフィス用'),
--       ('料理店用'),
--       ('自宅用'),
--       ('キャンプ用'),
--       ('クッション性抜群'),
--       ('モーター付き'),
--       ('ベッド一体型'),
--       ('ディスプレイ配置可能'),
--       ('ミニ机付き'),
--       ('スピーカー付属'),
--       ('中国製'),
--       ('アンティーク'),
--       ('折りたたみ可能'),
--       ('重さ500g以内'),
--       ('24回払い無金利'),
--       ('現代的デザイン'),
--       ('近代的なデザイン'),
--       ('ルネサンス的なデザイン'),
--       ('アームなし'),
--       ('オーダーメイド可能'),
--       ('ポリカーボネート製'),
--       ('フットレスト付き');

-- INSERT INTO isuumo.estate_feature (feature) VALUES
--       ('最上階'),
--       ('防犯カメラ'),
--       ('ウォークインクローゼット'),
--       ('ワンルーム'),
--       ('ルーフバルコニー付'),
--       ('エアコン付き'),
--       ('駐輪場あり'),
--       ('プロパンガス'),
--       ('駐車場あり'),
--       ('防音室'),
--       ('追い焚き風呂'),
--       ('オートロック'),
--       ('即入居可'),
--       ('IHコンロ'),
--       ('敷地内駐車場'),
--       ('トランクルーム'),
--       ('角部屋'),
--       ('カスタマイズ可'),
--       ('DIY可'),
--       ('ロフト'),
--       ('シューズボックス'),
--       ('インターネット無料'),
--       ('地下室'),
--       ('敷地内ゴミ置場'),
--       ('管理人有り'),
--       ('宅配ボックス'),
--       ('ルームシェア可'),
--       ('セキュリティ会社加入済'),
--       ('メゾネット'),
--       ('女性限定'),
--       ('バイク置場あり'),
--       ('エレベーター'),
--       ('ペット相談可'),
--       ('洗面所独立'),
--       ('都市ガス'),
--       ('浴室乾燥機'),
--       ('インターネット接続可'),
--       ('テレビ・通信'),
--       ('専用庭'),
--       ('システムキッチン'),
--       ('高齢者歓迎'),
--       ('ケーブルテレビ'),
--       ('床下収納'),
--       ('バス・トイレ別'),
--       ('駐車場2台以上'),
--       ('楽器相談可'),
--       ('フローリング'),
--       ('オール電化'),
--       ('TVモニタ付きインタホン'),
--       ('デザイナーズ物件');

CREATE INDEX cf_chair_feature_idx on isuumo.chairs_features (chair_id, feature_id);
CREATE INDEX ef_estate_feature_idx on isuumo.estates_features (estate_id, feature_id);
